<?php
declare(strict_types=1);
$oPath=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
if(!(($oPath==='/api/services')||strpos($oPath,'/api/service-orders')===0||$oPath==='/api/community/my-orders'))return false;
$oMethod=strtoupper($_SERVER['REQUEST_METHOD']??'GET');$oJson=static function(int $s,$v):void{http_response_code($s);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);};
$oCamel=static function(array $r):array{$out=[];foreach($r as $k=>$v){$k=preg_replace_callback('/_([a-z])/',static fn($m)=>strtoupper($m[1]),$k)??$k;if(is_string($v)&&preg_match('/^-?\d+$/',$v))$v=(int)$v;$out[$k]=$v;}return$out;};
try{$c=require dirname(__DIR__).'/private_html/alwdaif-migration-config.php';$pdo=new PDO(sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',$c['host'],$c['port'],$c['database']),$c['username'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 if($oPath==='/api/services'&&$oMethod==='GET'){$rows=$pdo->query('SELECT * FROM `services` WHERE `is_active`=1 ORDER BY `sort_order`,`id`')->fetchAll();$oJson(200,array_map($oCamel,$rows));return true;}
 $token=trim((string)($_SERVER['HTTP_X_COMMUNITY_TOKEN']??''));$mid=null;if($token!==''){$s=$pdo->prepare('SELECT `member_id` FROM `community_auth_tokens` WHERE `token_hash`=? AND `expires_at`>? LIMIT 1');$s->execute([hash('sha256',$token),(int)floor(microtime(true)*1000)]);$v=$s->fetchColumn();if($v!==false)$mid=(int)$v;}
 if(!$mid){$oJson(401,['message'=>'يجب تسجيل الدخول أولاً']);return true;}
 if($oPath==='/api/community/my-orders'&&$oMethod==='GET'){$s=$pdo->prepare('SELECT * FROM `service_orders` WHERE `member_id`=? ORDER BY `created_at` DESC');$s->execute([$mid]);$oJson(200,array_map($oCamel,$s->fetchAll()));return true;}
 if($oPath==='/api/service-orders'&&$oMethod==='POST'){$b=json_decode(file_get_contents('php://input')?:'{}',true);$slug=trim((string)($b['serviceSlug']??''));$name=trim((string)($b['serviceName']??''));$customer=trim((string)($b['customerName']??''));$phone=trim((string)($b['customerPhone']??''));if($slug===''||$name===''||$customer===''||$phone===''){$oJson(400,['message'=>'بيانات الطلب ناقصة']);return true;}$now=(int)floor(microtime(true)*1000);$num='ORD-'.strtoupper(base_convert((string)$now,10,36));$s=$pdo->prepare('INSERT INTO `service_orders` (`member_id`,`order_number`,`service_slug`,`service_name`,`service_variant`,`amount`,`customer_name`,`customer_phone`,`customer_email`,`receipt_url`,`payment_method`,`status`,`notes`,`created_at`,`updated_at`) VALUES (?,?,?,?,?,?,?,?,?,?,"bank_transfer","pending",?,?,?)');$s->execute([$mid,$num,$slug,$name,trim((string)($b['serviceVariant']??'')),(int)($b['amount']??0),$customer,$phone,trim((string)($b['customerEmail']??'')),trim((string)($b['receiptUrl']??'')),trim((string)($b['notes']??'')),$now,$now]);$id=(int)$pdo->lastInsertId();$s=$pdo->prepare('SELECT * FROM `service_orders` WHERE `id`=?');$s->execute([$id]);$oJson(201,$oCamel($s->fetch()));return true;}
 if(preg_match('#^/api/service-orders/([^/]+)$#',$oPath,$m)&&$oMethod==='GET'){$s=$pdo->prepare('SELECT * FROM `service_orders` WHERE `order_number`=? AND `member_id`=?');$s->execute([$m[1],$mid]);$row=$s->fetch();if(!$row){$oJson(404,['message'=>'الطلب غير موجود']);return true;}$oJson(200,$oCamel($row));return true;}
 return false;
}catch(Throwable $e){error_log('Cloudways orders API error: '.$e->getMessage());$oJson(500,['message'=>'تعذر إكمال العملية']);return true;}
