<?php
declare(strict_types=1);
$spPath=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
if(strpos($spPath,'/api/support')!==0)return false;
$spRoute=substr($spPath,12)?:'/';$spMethod=strtoupper($_SERVER['REQUEST_METHOD']??'GET');
$spJson=static function(int $status,$value):void{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);};
$spCamel=static function(array $row):array{$out=[];foreach($row as $k=>$v){$k=preg_replace_callback('/_([a-z])/',static fn($m)=>strtoupper($m[1]),$k)??$k;if(is_string($v)&&preg_match('/^-?\d+$/',$v))$v=(int)$v;$out[$k]=$v;}return $out;};
try{
 $c=require dirname(__DIR__).'/private_html/alwdaif-migration-config.php';$pdo=new PDO(sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',$c['host'],$c['port'],$c['database']),$c['username'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 $token=trim((string)($_SERVER['HTTP_X_COMMUNITY_TOKEN']??''));$mid=null;if($token!==''){$s=$pdo->prepare('SELECT `member_id` FROM `community_auth_tokens` WHERE `token_hash`=? AND `expires_at`>? LIMIT 1');$s->execute([hash('sha256',$token),(int)floor(microtime(true)*1000)]);$x=$s->fetchColumn();if($x!==false)$mid=(int)$x;}
 if(!$mid){$spJson(401,['message'=>'يجب تسجيل الدخول أولاً']);return true;}
 if($spRoute==='/tickets'&&$spMethod==='GET'){$s=$pdo->prepare('SELECT * FROM `support_tickets` WHERE `member_id`=? ORDER BY `updated_at` DESC');$s->execute([$mid]);$spJson(200,array_map($spCamel,$s->fetchAll()));return true;}
 if($spRoute==='/tickets'&&$spMethod==='POST'){$b=json_decode(file_get_contents('php://input')?:'{}',true);$subject=trim((string)($b['subject']??''));$type=trim((string)($b['type']??''));$message=trim((string)($b['message']??''));if($subject===''||$type===''||$message===''){$spJson(400,['message'=>'الموضوع والنوع والرسالة مطلوبة']);return true;}$now=(int)floor(microtime(true)*1000);$num='TKT-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6));$pdo->beginTransaction();try{$s=$pdo->prepare('INSERT INTO `support_tickets` (`ticket_number`,`member_id`,`subject`,`type`,`status`,`order_number`,`last_member_reply_at`,`created_at`,`updated_at`) VALUES (?,?,?,? ,"open",?,?,?,?)');$s->execute([$num,$mid,$subject,$type,trim((string)($b['orderNumber']??''))?:null,$now,$now,$now]);$id=(int)$pdo->lastInsertId();$s=$pdo->prepare('INSERT INTO `support_ticket_replies` (`ticket_id`,`sender_id`,`sender_type`,`message`,`created_at`) VALUES (?, ?,"member",?,?)');$s->execute([$id,$mid,$message,$now]);$pdo->commit();}catch(Throwable $e){$pdo->rollBack();throw $e;}$s=$pdo->prepare('SELECT * FROM `support_tickets` WHERE `id`=?');$s->execute([$id]);$spJson(201,$spCamel($s->fetch()));return true;}
 if(preg_match('#^/tickets/(\d+)$#',$spRoute,$m)&&$spMethod==='GET'){$s=$pdo->prepare('SELECT * FROM `support_tickets` WHERE `id`=? AND `member_id`=?');$s->execute([(int)$m[1],$mid]);$ticket=$s->fetch();if(!$ticket){$spJson(404,['message'=>'التذكرة غير موجودة']);return true;}$s=$pdo->prepare('SELECT * FROM `support_ticket_replies` WHERE `ticket_id`=? ORDER BY `created_at`,`id`');$s->execute([(int)$m[1]]);$spJson(200,['ticket'=>$spCamel($ticket),'replies'=>array_map($spCamel,$s->fetchAll())]);return true;}
 if(preg_match('#^/tickets/(\d+)/reply$#',$spRoute,$m)&&$spMethod==='POST'){$b=json_decode(file_get_contents('php://input')?:'{}',true);$message=trim((string)($b['message']??''));if($message===''){$spJson(400,['message'=>'الرسالة مطلوبة']);return true;}$s=$pdo->prepare('SELECT `status` FROM `support_tickets` WHERE `id`=? AND `member_id`=?');$s->execute([(int)$m[1],$mid]);$status=$s->fetchColumn();if($status===false){$spJson(404,['message'=>'التذكرة غير موجودة']);return true;}if($status==='closed'){$spJson(400,['message'=>'التذكرة مغلقة']);return true;}$now=(int)floor(microtime(true)*1000);$s=$pdo->prepare('INSERT INTO `support_ticket_replies` (`ticket_id`,`sender_id`,`sender_type`,`message`,`created_at`) VALUES (?, ?,"member",?,?)');$s->execute([(int)$m[1],$mid,$message,$now]);$id=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE `support_tickets` SET `status`="open",`last_member_reply_at`=?,`updated_at`=? WHERE `id`=?')->execute([$now,$now,(int)$m[1]]);$s=$pdo->prepare('SELECT * FROM `support_ticket_replies` WHERE `id`=?');$s->execute([$id]);$spJson(201,$spCamel($s->fetch()));return true;}
 if(preg_match('#^/tickets/(\d+)/reopen$#',$spRoute,$m)&&$spMethod==='POST'){$s=$pdo->prepare('UPDATE `support_tickets` SET `status`="open",`closed_at`=NULL,`updated_at`=? WHERE `id`=? AND `member_id`=? AND `status`="closed"');$s->execute([(int)floor(microtime(true)*1000),(int)$m[1],$mid]);if(!$s->rowCount()){$spJson(400,['message'=>'التذكرة مفتوحة بالفعل أو غير موجودة']);return true;}$spJson(200,['success'=>true]);return true;}
 return false;
}catch(Throwable $e){error_log('Cloudways support API error: '.$e->getMessage());$spJson(500,['message'=>'تعذر إكمال العملية']);return true;}
