import { db } from "./db";
import { employerJobs } from "@workspace/db";
import { count } from "drizzle-orm";

const SEED_DATA = [
  {
    title: "مطوّر تطبيقات جوال",
    company: "شركة الأفق للتقنية",
    region: "الرياض",
    city: "الرياض",
    description: "نبحث عن مطوّر تطبيقات جوال متمرّس للانضمام إلى فريقنا المبدع، مع خبرة في Flutter أو React Native.",
    requirements: "خبرة لا تقل عن سنتين - إتقان Flutter أو React Native - إجادة اللغة الإنجليزية",
    targetGender: "all",
    targetNationality: "saudi",
    contactMethod: "email",
    contactValue: "hr@ufq.sa",
    submitterName: "أحمد العتيبي",
    submitterEmail: "hr@ufq.sa",
    status: "published",
    deadlineDate: new Date("2026-07-01"),
    viewCount: 69,
    workSchedule: "full_time",
    workMode: "remote",
  },
  {
    title: "مدير مبيعات إقليمي",
    company: "مجموعة النخبة التجارية",
    region: "المنطقة الشرقية",
    city: "الدمام",
    description: "قيادة فريق المبيعات وتحقيق أهداف الإيرادات الفصلية في منطقة الشرق.",
    requirements: "خبرة 5 سنوات في المبيعات - مهارات قيادية - رخصة قيادة سارية",
    targetGender: "male",
    targetNationality: "all",
    contactMethod: "email",
    contactValue: "jobs@nokhba-group.com",
    submitterName: "سلطان القحطاني",
    submitterEmail: "sultan@nokhba.com",
    status: "published",
    deadlineDate: new Date("2026-06-15"),
    viewCount: 98,
    workSchedule: "full_time",
    workMode: "on_site",
  },
  {
    title: "ممرضة قسم طوارئ",
    company: "مستشفى الرعاية الذهبية",
    region: "مكة المكرمة",
    city: "مكة المكرمة",
    description: "تقديم الرعاية التمريضية للمرضى في قسم الطوارئ على مدار الساعة.",
    requirements: "دبلوم أو بكالوريوس تمريض - رخصة مزاولة مهنة سارية - خبرة سنة على الأقل",
    targetGender: "female",
    targetNationality: "all",
    contactMethod: "phone",
    contactValue: "0556677889",
    submitterName: "فاطمة الغامدي",
    submitterEmail: "fatima@golden-care.sa",
    status: "published",
    deadlineDate: new Date("2026-06-30"),
    viewCount: 112,
    workSchedule: "full_time",
    workMode: "on_site",
  },
  {
    title: "مهندس مدني",
    company: "شركة البناء الحديث",
    region: "المدينة المنورة",
    city: "المدينة المنورة",
    description: "الإشراف على مشاريع البنية التحتية ومتابعة تنفيذ الخطط الهندسية.",
    requirements: "بكالوريوس هندسة مدنية - خبرة 3 سنوات - عضوية هيئة المهندسين",
    targetGender: "male",
    targetNationality: "all",
    contactMethod: "email",
    contactValue: "eng@modernconstruct.com",
    submitterName: "عبدالله الزهراني",
    submitterEmail: "hr@modernconstruct.com",
    status: "published",
    deadlineDate: new Date("2026-07-15"),
    viewCount: 45,
    workSchedule: "full_time",
    workMode: "on_site",
  },
  {
    title: "معلم برمجة للناشئين",
    company: "أكاديمية المستقبل التعليمية",
    region: "مكة المكرمة",
    city: "جدة",
    description: "تدريس أساسيات البرمجة بأساليب تفاعلية وممتعة لطلاب الفئة العمرية 8-17 سنة.",
    requirements: "إجادة إحدى لغات البرمجة - مهارات تواصل عالية - خبرة تدريسية مفضّلة",
    targetGender: "all",
    targetNationality: "saudi",
    contactMethod: "url",
    contactValue: "https://futuracademy.sa/jobs",
    submitterName: "منى الشهري",
    submitterEmail: "mona@futuracademy.sa",
    status: "published",
    deadlineDate: new Date("2026-08-01"),
    viewCount: 67,
    workSchedule: "part_time",
    workMode: "on_site",
  },
  {
    title: "سائق توصيل (دوام جزئي)",
    company: "شركة لوجستيكس برو",
    region: "الرياض",
    city: "الرياض",
    description: "توصيل الطلبات لعملائنا داخل نطاق مدينة الرياض بشكل سريع واحترافي.",
    requirements: "رخصة قيادة سارية - معرفة بمناطق الرياض - هاتف ذكي",
    targetGender: "male",
    targetNationality: "all",
    contactMethod: "phone",
    contactValue: "0509988776",
    submitterName: "محمد السالم",
    submitterEmail: "hr@logisticspro.sa",
    status: "published",
    deadlineDate: new Date("2026-06-20"),
    viewCount: 201,
    workSchedule: "part_time",
    workMode: "on_site",
  },
  {
    title: "مصمم جرافيك أول",
    company: "استوديو إبداع للتصميم",
    region: "الرياض",
    city: "الرياض",
    description: "تصميم هويات بصرية ومواد تسويقية لعملاء من مختلف القطاعات.",
    requirements: "بكالوريوس تصميم أو ما يعادله - إتقان Adobe Suite - ملف أعمال (Portfolio)",
    targetGender: "all",
    targetNationality: "all",
    contactMethod: "email",
    contactValue: "design@ebda3studio.com",
    submitterName: "ريم العسيري",
    submitterEmail: "reem@ebda3studio.com",
    status: "published",
    deadlineDate: new Date("2026-07-10"),
    viewCount: 90,
    workSchedule: "full_time",
    workMode: "remote",
  },
  {
    title: "طاهٍ متخصص في المطبخ السعودي",
    company: "مطاعم البيت السعودي",
    region: "القصيم",
    city: "بريدة",
    description: "إعداد وطهي الأطباق السعودية التقليدية بجودة عالية وفق معايير المطعم.",
    requirements: "خبرة 3 سنوات في الطهي السعودي - شهادة سلامة غذائية مفضّلة",
    targetGender: "male",
    targetNationality: "all",
    contactMethod: "phone",
    contactValue: "0512233445",
    submitterName: "ناصر الدوسري",
    submitterEmail: "chef@saudihome-rest.com",
    status: "published",
    deadlineDate: null,
    viewCount: 54,
    workSchedule: "full_time",
    workMode: "on_site",
  },
  {
    title: "محاسب قانوني",
    company: "شركة رؤية للاستشارات المالية",
    region: "الرياض",
    city: "الرياض",
    description: "إعداد القوائم المالية والتقارير الضريبية ومراجعة الحسابات للعملاء.",
    requirements: "بكالوريوس محاسبة - شهادة CPA أو SOCPA مفضّلة - خبرة 4 سنوات",
    targetGender: "all",
    targetNationality: "saudi",
    contactMethod: "url",
    contactValue: "https://roia-consulting.sa/careers",
    submitterName: "خالد الشمري",
    submitterEmail: "khalid@roia-consulting.sa",
    status: "published",
    deadlineDate: new Date("2026-08-15"),
    viewCount: 44,
    workSchedule: "full_time",
    workMode: "on_site",
  },
  {
    title: "مدرب لياقة بدنية",
    company: "مركز لياقة باور فيت",
    region: "تبوك",
    city: "تبوك",
    description: "تصميم وتنفيذ برامج تدريبية مخصصة للأعضاء وتحفيزهم لتحقيق أهدافهم الصحية.",
    requirements: "شهادة تدريب معتمدة (ACE أو NASM أو ما يعادلها) - خبرة سنتان",
    targetGender: "all",
    targetNationality: "all",
    contactMethod: "email",
    contactValue: "coach@powerfit-tabuk.com",
    submitterName: "لينا المطيري",
    submitterEmail: "lina@powerfit-tabuk.com",
    status: "published",
    deadlineDate: null,
    viewCount: 30,
    workSchedule: "part_time",
    workMode: "on_site",
  },
  {
    title: "مهندس معماري",
    company: "شركة الإنشاءات الحديثة",
    region: "الرياض",
    city: "الرياض",
    description: "مطلوب مهندس معماري لتصميم المشاريع السكنية والتجارية.",
    requirements: "بكالوريوس هندسة معمارية\nخبرة 3 سنوات على الأقل",
    targetGender: "male",
    targetNationality: "saudi",
    contactMethod: "email",
    contactValue: "arch@modernconstruct.com",
    submitterName: "المدير",
    submitterEmail: "hr@modernconstruct.com",
    status: "published",
    deadlineDate: new Date("2026-09-01"),
    viewCount: 2,
    workSchedule: "full_time",
    workMode: "on_site",
  },
  {
    title: "مطوّر واجهات أمامية",
    company: "شركة الأفق للتقنية",
    region: "الرياض",
    city: "الرياض",
    description: "مطلوب مطوّر واجهات أمامية بخبرة في React وVue.",
    requirements: "خبرة 2 سنة في تطوير الويب\nإتقان React أو Vue",
    targetGender: "all",
    targetNationality: "all",
    contactMethod: "email",
    contactValue: "dev@ufq.sa",
    submitterName: "المدير التقني",
    submitterEmail: "hr@ufq.sa",
    status: "published",
    deadlineDate: new Date("2026-09-01"),
    viewCount: 4,
    workSchedule: "full_time",
    workMode: "remote",
  },
  {
    title: "مطوّر تطبيقات ويب",
    company: "شركة نخبة التقنية",
    region: "المنطقة الشرقية",
    city: "الدمام",
    description: "نبحث عن مطوّر تطبيقات ويب متكاملة.",
    requirements: "إتقان Node.js أو Python\nخبرة في قواعد البيانات",
    targetGender: "all",
    targetNationality: "all",
    contactMethod: "url",
    contactValue: "https://nokhba-tech.sa/jobs",
    submitterName: "مدير التوظيف",
    submitterEmail: "hr@nokhba-tech.sa",
    status: "published",
    deadlineDate: new Date("2026-09-10"),
    viewCount: 2,
    workSchedule: "full_time",
    workMode: "remote",
  },
  {
    title: "مصمم جرافيك وهوية بصرية",
    company: "وكالة الإبداع التسويقية",
    region: "الرياض",
    city: "الرياض",
    description: "نبحث عن مصمم جرافيك مبدع لتطوير الهويات البصرية.",
    requirements: "خبرة لا تقل عن 3 سنوات\nإتقان Adobe Suite",
    targetGender: "all",
    targetNationality: "all",
    contactMethod: "email",
    contactValue: "creative@ibd3.sa",
    submitterName: "مدير الإبداع",
    submitterEmail: "hr@ibd3.sa",
    status: "published",
    deadlineDate: new Date("2026-08-20"),
    viewCount: 6,
    workSchedule: "full_time",
    workMode: "on_site",
  },
  {
    title: "مدير مبيعات",
    company: "مجموعة الرائد التجارية",
    region: "الرياض",
    city: "الرياض",
    description: "مطلوب مدير مبيعات لقيادة فريق المبيعات وتحقيق الأهداف.",
    requirements: "خبرة 5 سنوات في المبيعات\nمهارات قيادية عالية",
    targetGender: "male",
    targetNationality: "saudi",
    contactMethod: "phone",
    contactValue: "0501122334",
    submitterName: "مدير الموارد البشرية",
    submitterEmail: "hr@raidalcommerce.sa",
    status: "published",
    deadlineDate: new Date("2026-09-15"),
    viewCount: 3,
    workSchedule: "full_time",
    workMode: "on_site",
  },
];

export async function seedEmployerJobsIfEmpty(): Promise<void> {
  try {
    const [{ value }] = await db.select({ value: count() }).from(employerJobs);
    if (value > 0) {
      console.log(`[seed] employer_jobs already has ${value} rows — skipping seed`);
      return;
    }
    console.log("[seed] employer_jobs is empty — seeding initial data...");
    await db.insert(employerJobs).values(SEED_DATA as any);
    console.log(`[seed] inserted ${SEED_DATA.length} employer jobs`);
  } catch (err) {
    console.error("[seed] failed to seed employer jobs:", err);
  }
}
